name: libxd
description: A libx-esque Collection infrastructure for MobX applications.
version: 1.1.0
homepage: https://github.com/Manguelo/libxd

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  mobx: ^2.0.5

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.1+2

flutter:
